import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";

// Components
import ChatBox from "../components/chatBox";

// Actions
import { logout } from "../redux/actions/authActions";
import { useAuth } from "../hooks/useAuth";

export default function Home() {
	const router = useRouter();
	const dispatch = useDispatch();
	const { isAuthenticated } = useAuth();

	if (!isAuthenticated) {
		return (
			<div className={styles.container}>
				<h1>User not Loogged in!!!</h1>
				<button
					onClick={() => router.push("/login")}
					className="py-2 px-4 text-base border border-black border-opacity-40"
				>
					LOGIN
				</button>
			</div>
		);
	}

	const _logout = () => {
		dispatch(logout());
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="py-2 px-4 w-full flex justify-end">
				<button
					onClick={_logout}
					className="py-2 px-4 text-base border border-black border-opacity-40"
				>
					Logout
				</button>
			</div>
			<h1 className="pb-6 md:text-2xl text-xl text-center">
				A simple chat app with{" "}
				<span className="text-blue-400 font-medium">Socket IO</span> &{" "}
				<span className="text-yellow-400 font-medium">JWT</span> Authentication
			</h1>
			<ChatBox />
		</div>
	);
}
